### ISSUE TITLE
2499_DRT - wrong tone curve for HLG?

### ISSUE THREAD

**Issue by ghost** [JuanPabloZambrano/DCTL#1]
Hi, is the tone curve for HLG correct? It is brighter compared to BT.1886 one, when it usually is darker to match the SDR image (like in ACES). The output image is also "too bright" or "has too much contrast" compared to the SDR grade when viewing side by side (exposure adjusted)

**Comment by JuanPabloZambrano** [comment]
The HLG is correct, I double check, you can try it yourself by setting it to PQ and then using a CST from PQ to linear without tone mapping , then do the same but with HLG and both give the same values. The difference you are seen is that I am re-encoding the SDR image to HDR via gain so we get the same image in HDR and SDR, you can use the diffuse white knob to set your peak, this will increase your middle grey but that by design as we want to always keep the relative relationships of the image.

**Comment by JuanPabloZambrano** [comment]
Agree to disagree, I have the same point of view on HDR as Troy, and he is not the only one. Even PQ arguably is broken, hence why Dolby create IQ to try to "fix" it, absolute luminance is not a thing, its about relative values.
